// GENERATED by tools/train_autoencoder.py -- tiny autoencoder for the on-chip detector.
// 5->3->5, tanh hidden layer, trained on 752 normal windows (2026-10-03); 152 bytes of weights.
// Build with -DHAVE_AE_MODEL=0 (or #define it before including) to fall back to z-scores.
#pragma once
#ifndef HAVE_AE_MODEL
#define HAVE_AE_MODEL 1
#endif
#if HAVE_AE_MODEL
#define AE_HIDDEN 3
static const float AE_THRESHOLD = 2.70177f;
static const float AE_CLIP = 20.0f;
static const float AE_W1[5][3] = {
  {0.1299139f, 0.05017459f, -0.1272506f},
  {-0.05156036f, 0.07042157f, -0.03484652f},
  {-0.09752069f, 0.09822922f, -0.05476101f},
  {0.07768422f, -0.09475853f, 0.03799402f},
  {-0.08093783f, -0.1313704f, -0.1031109f}};
static const float AE_B1[3] = {-0.02376734f, -0.004841778f, 0.05903352f};
static const float AE_W2[3][5] = {
  {3.583583f, -1.138807f, -2.184569f, 1.758182f, -2.199724f},
  {1.051483f, 1.543525f, 2.062603f, -2.057395f, -3.751296f},
  {-4.183869f, -0.8327867f, -1.32263f, 0.823325f, -3.7447f}};
static const float AE_B2[5] = {0.3215632f, 0.01454849f, 0.3457085f, 0.3290707f, 0.1089983f};
#endif
