"""Generate per-node keys and configs.

Writes (all gitignored):
  config/nodes.json             real LAN config; IPs default to "auto" (discovered at runtime)
  config/local.json             same keys, every device on its own 127.0.0.x for a one-laptop run
  firmware/hive_node/secrets.h  Wi-Fi + keys + tunables for the ESP32 node

Existing keys are reused unless --rotate is given, so re-running (e.g. to change the Wi-Fi
password) never invalidates devices that were already flashed.

  python tools/provision_keys.py
  python tools/provision_keys.py --ssid HiveNet --password secret123 --led-pin 2
"""

import argparse
import json
import os
import secrets
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "agent"))
import hive_core  # noqa: E402

NODES_JSON = os.path.join(ROOT, "config", "nodes.json")
LOCAL_JSON = os.path.join(ROOT, "config", "local.json")
SECRETS_H = os.path.join(ROOT, "firmware", "hive_node", "secrets.h")

# Loopback addresses for the one-laptop simulation (see DECISIONS.md).
LOCAL_HUB = "127.0.0.1"
LOCAL_NODE_BASE = 2
LOCAL_BULB = "127.0.0.20"
LOCAL_ATTACKER = "127.0.0.66"


def new_key():
    return secrets.token_hex(32)


def build(old, node_specs, rotate):
    old_keys = {} if rotate or not old else {
        e["node_id"]: e["key"] for e in old.get("nodes", []) + old.get("issuers", [])}

    def key(nid):
        return old_keys.get(nid) or new_key()

    cfg = {
        "network": dict(hive_core.NETWORK_DEFAULTS),
        "hub": {"node_id": "hub", "ip": "auto"},
        "dashboard": {"ip": "auto"},
        "attacker": {"ip": "auto"},
        "dumb": {"name": "bulb", "ip": "auto"},
        "quorum": 2,
        "nodes": [{"node_id": nid, "kind": kind, "key": key(nid), "ip": "auto"}
                  for nid, kind in node_specs],
        "issuers": [
            {"node_id": "gateway", "kind": "gateway", "key": key("gateway"), "ip": "auto"},
            {"node_id": "rogue", "kind": "sim", "key": key("rogue"),
             "note": "a 'compromised' Hive device used only by the attack-the-cure scenarios"},
        ],
        "admin_key": (old or {}).get("admin_key") if old and not rotate else new_key(),
        "protected": [],
        "demo": dict(hive_core.DEMO_DEFAULTS),
    }
    if old:  # keep hand-edited settings
        for section in ("network", "hub", "dashboard", "attacker", "dumb", "demo"):
            cfg[section].update(old.get(section, {}))
        for k in ("quorum", "protected"):
            cfg[k] = old.get(k, cfg[k])
        old_ips = {e["node_id"]: e.get("ip", "auto") for e in old.get("nodes", []) + old.get("issuers", [])}
        for e in cfg["nodes"] + cfg["issuers"]:
            if e["node_id"] in old_ips:
                e["ip"] = old_ips[e["node_id"]]
    cfg["admin_key"] = cfg["admin_key"] or new_key()
    return cfg


def localize(cfg):
    """Same keys, loopback IPs, no broadcast (loopback has none: vaccines go unicast)."""
    loc = json.loads(json.dumps(cfg))
    loc["network"]["broadcast"] = None
    loc["hub"]["ip"] = LOCAL_HUB
    loc["dashboard"]["ip"] = LOCAL_HUB
    loc["attacker"]["ip"] = LOCAL_ATTACKER
    loc["dumb"]["ip"] = LOCAL_BULB
    for i, e in enumerate(loc["nodes"]):
        e["ip"] = f"127.0.0.{LOCAL_NODE_BASE + i}"
        if e["kind"] == "esp32":
            e["kind"] = "esp32-sim"   # a Python stand-in until the real board joins
    for e in loc["issuers"]:
        if e["node_id"] == "gateway":
            e["ip"] = LOCAL_HUB
    return loc


def c_str(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def secrets_header(cfg, node_id, ssid, password, led_pin, led_active_low):
    node = hive_core.node_entry(cfg, node_id)
    net, demo = cfg["network"], cfg["demo"]
    hub_ip = hive_core.static_ip(cfg["hub"]["ip"]) or ""
    dash_ip = hive_core.static_ip(cfg["dashboard"]["ip"]) or ""
    issuers = [e for e in cfg["nodes"] + cfg["issuers"] if e["node_id"] != node_id]
    lines = [
        "// GENERATED by tools/provision_keys.py -- do not commit (gitignored).",
        "#pragma once",
        "",
        f"#define WIFI_SSID {c_str(ssid)}",
        f"#define WIFI_PASS {c_str(password)}",
        "",
        f"#define NODE_ID {c_str(node_id)}",
        f"#define NODE_KEY_HEX {c_str(node['key'])}",
        f"#define ADMIN_KEY_HEX {c_str(cfg['admin_key'])}",
        "",
        f"#define DATA_PORT {net['data_port']}",
        f"#define VAX_PORT {net['vax_port']}",
        f"#define STATUS_PORT {net['status_port']}",
        # "auto" on the ESP32 = 255.255.255.255 plus the subnet broadcast it computes itself
        f"#define BROADCAST_IP {c_str(net['broadcast'] if net['broadcast'] not in (None, 'auto') else '255.255.255.255')}",
        f"#define HUB_IP {c_str(hub_ip)}            // \"\" = learn from the first hub command",
        f"#define DASHBOARD_IP {c_str(dash_ip)}      // \"\" = same as hub",
        "",
        f"#define LED_PIN {led_pin}",
        f"#define LED_ACTIVE_LOW {1 if led_active_low else 0}",
        "",
        f"#define QUORUM {cfg['quorum']}",
        f"#define LEARN_SECONDS {demo['learn_seconds']}",
        f"#define WINDOW_MS {int(float(demo['window_seconds']) * 1000)}",
        f"#define THRESHOLD {float(demo['threshold'])}f",
        f"#define CONSECUTIVE {demo['consecutive']}",
        f"#define QUARANTINE_HOLD_S {demo['quarantine_hold_s']}",
        f"#define VAX_TTL_S {demo['vax_ttl_s']}",
        f"#define VAX_RATE_MAX_PER_MIN {demo['vax_rate_max_per_min']}",
        f"#define DISTRUST_S {demo['distrust_s']}",
        f"#define PENDING_S {demo['pending_s']}",
        "",
        "struct IssuerKey { const char* id; const char* key_hex; };",
        "static const IssuerKey ISSUERS[] = {",
    ]
    lines += [f"  {{{c_str(e['node_id'])}, {c_str(e['key'])}}}," for e in issuers]
    lines += ["};", "static const int N_ISSUERS = sizeof(ISSUERS) / sizeof(ISSUERS[0]);", ""]
    return "\n".join(lines)


def write_json(path, obj):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(obj, f, indent=2)
        f.write("\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--nodes", default="esp32:esp32,lapA:python,lapB:python",
                    help="comma list of node_id:kind")
    ap.add_argument("--esp32-node", default="esp32", help="which node secrets.h is written for")
    ap.add_argument("--ssid", default="HiveNet")
    ap.add_argument("--password", default="change-me-please")
    ap.add_argument("--led-pin", type=int, default=2)
    ap.add_argument("--led-active-low", action="store_true")
    ap.add_argument("--quorum", type=int, help="distinct issuers needed to adopt a vaccine "
                                                "(default 2; use 1 with only two immune nodes)")
    ap.add_argument("--broadcast", help="vaccine/status broadcast address for the LAN config ('auto' = "
                                        "directed /24 broadcast + 255.255.255.255)")
    ap.add_argument("--rotate", action="store_true", help="generate fresh keys for everyone")
    args = ap.parse_args()

    specs = [tuple(s.split(":", 1)) for s in args.nodes.split(",") if s]
    old = None
    if os.path.exists(NODES_JSON):
        with open(NODES_JSON, "r", encoding="utf-8") as f:
            old = json.load(f)
    cfg = build(old, specs, args.rotate)
    if args.quorum is not None:
        cfg["quorum"] = max(1, args.quorum)
    if args.broadcast:
        cfg["network"]["broadcast"] = args.broadcast
    write_json(NODES_JSON, cfg)
    write_json(LOCAL_JSON, localize(cfg))
    print(f"wrote {os.path.relpath(NODES_JSON, ROOT)} and {os.path.relpath(LOCAL_JSON, ROOT)}"
          f" ({'new' if args.rotate or not old else 'kept existing'} keys)")

    if any(nid == args.esp32_node for nid, _ in specs):
        os.makedirs(os.path.dirname(SECRETS_H), exist_ok=True)
        with open(SECRETS_H, "w", encoding="utf-8", newline="\n") as f:
            f.write(secrets_header(cfg, args.esp32_node, args.ssid, args.password,
                                   args.led_pin, args.led_active_low))
        print(f"wrote {os.path.relpath(SECRETS_H, ROOT)} for node '{args.esp32_node}'")


if __name__ == "__main__":
    main()
